### ISSUE TITLE
[Bug]: Check extra741, 742 throws detect_secret error; sometimes fails for same resource sometimes passes

### ISSUE THREAD

**Issue by romgitrom** [toniblyx/prowler#1060] opened 2022-03-08 04:45 UTC
**What happened?**  
Check Extra 7.41 and 7.42 show status as pass and fail for the same resource on different occasions. It also throws a detect_secret syntax error while having the latest version or detect_secrets library installed.

**How to reproduce it**  
1. sudo ./prowler -c extra741
2. sudo ./prowler -c extra742
3. Single account environment
4. Detect_secrets error:
Traceback (most recent call last):
  File "/bin/detect-secrets", line 5, in <module>
    from detect_secrets.main import main
  File "/usr/lib/python2.7/site-packages/detect_secrets/__init__.py", line 1, in <module>
    from .core.secrets_collection import SecretsCollection  # noqa: F401
  File "/usr/lib/python2.7/site-packages/detect_secrets/core/secrets_collection.py", line 18
    path: str
        ^
SyntaxError: invalid syntax

5. With an earlier version of detect_secrets the same resource shows as PASS which now shows as FAIL

**Expected behavior**  
Per the above syntax error the check execution stops if -M command is provided with a format to be saved. The error stays the same with latest version of prowler tool. Current version in use:2.4.0-07042021.

**Screenshots or Logs**  
![image](https://user-images.githubusercontent.com/101163016/157167753-606b4fdf-d3a9-4a30-9808-ea1d65833644.png)

**From where are you running Prowler?**  
Please, complete the following information:
 - Resource: EC2 instance
 - OS: Amazon Linux 2
 - AWS-CLI Version [`aws --version`]:aws-cli/1.18.147 Python/2.7.18 Linux/4.14.232-177.418.amzn2.x86_64 botocore/1.18.6
 - Prowler Version [`./prowler -V`]:2.4.0-07042021
 - Shell and version:GNU bash, version 4.2.46(2)-release (x86_64-koji-linux-gnu)
 - Others:detect-secrets-1.1.0

**Additional context**
Could you please look into this.

**Comment by jfagoagas** [comment] 2022-03-18 11:42
Hi @romgitrom we are investigating it but last version of `detect-secrets` is `v.1.2.0` https://github.com/Yelp/detect-secrets/releases/tag/v1.2.0.

Please re-test this issue with Prowler v.2.8.0, which is the latest release https://github.com/prowler-cloud/prowler/releases/tag/2.8.0

Also, we've identified a bug in `check742`.

**Comment by jfagoagas** [comment] 2022-03-18 12:13
Please, @romgitrom check this PR https://github.com/prowler-cloud/prowler/pull/1078 and test it with the latest version of  `detect-secrets`.

Thank you!!

**Comment by romgitrom** [comment] 2022-03-24 07:31
Hi,
 
Thanks for looking into this, after updating prowler to v2.8.0 and detect_secrets to 1.2.0 there were some different errors.

python --version
Python 3.7.10

with detect_secrets==1.2.0:-

pip3 install detect_secrets==1.2.0
![image](https://user-images.githubusercontent.com/101163016/159863545-d8e38a56-f421-4266-9dcf-7cb440f7856d.png)

sudo pip3 install detect_secrets==1.2.0
![image](https://user-images.githubusercontent.com/101163016/159863758-26fd7dc4-0498-4389-9253-33e24bcff3fe.png)

sudo ./prowler -c extra741
![image](https://user-images.githubusercontent.com/101163016/159863829-1584f994-18ea-492c-90cf-a7143cbd0622.png)

![image](https://user-images.githubusercontent.com/101163016/159864009-e661b003-3af9-42bd-a68f-3de8066087ac.png)


with detect_secrets==1.1.0:-
![image](https://user-images.githubusercontent.com/101163016/159864537-036be790-0ecd-4dcf-afdb-3d66d3990124.png)


Could you please help me understand if it is a python version or detect_secrets or prowler tool issue.

Thank you in advance.

**Comment by jfagoagas** [comment] 2022-03-24 08:58
Hi @romgitrom, I think you have some kind of problem with your python environment.

I can't reproduce your issue. Please follow these steps to test another approach:
1. Run `virtualenv -p $(which python3) venv && source venv/bin/activate`
2. Run `pip install detect-secrets`
<img width="1276" alt="Screenshot 2022-03-24 at 09 50 33" src="https://user-images.githubusercontent.com/16007882/159878289-ab52a62f-891b-4355-95b1-674dad0db8f4.png">

As you can see is a fresh new environment.

Then, `./prowler -c extra741 -f us-east-1` (I have included `-f` to check only one region)

<img width="1207" alt="Screenshot 2022-03-24 at 09 55 14" src="https://user-images.githubusercontent.com/16007882/159879680-ded9a300-854f-4409-8ef5-6531ab638523.png">

**Comment by jfagoagas** [comment] 2022-03-28 09:33
Hi @romgitrom, we are closing this issue. Please, feel free to reopen it if you can provide us more information.

Thanks!

**Closed as completed by jfagoagas** 2022-03-28 09:33 UTC
Labels: bug, severity/medium
