### ISSUE TITLE
[Bug]: Could not connect to the endpoint URL: "https://sts.us-east.amazonaws.com/"

### ISSUE THREAD

**Issue by fgont** [toniblyx/prowler#1654] opened 2023-01-04 16:17 UTC
**What happened?**

Installed prowler, configured aws credendials, but when running it as
   prowler aws 

I got:

```prowler aws
                         _
 _ __  _ __ _____      _| | ___ _ __
| '_ \| '__/ _ \ \ /\ / / |/ _ \ '__|
| |_) | | | (_) \ V  V /| |  __/ |
| .__/|_|  \___/ \_/\_/ |_|\___|_|v3.0.1
|_| the handy cloud security tool

Date: 2023-01-04 16:04:26

2023-01-04 16:04:37,934 [File: audit_info.py:30] 	[Module: audit_info]	 CRITICAL: EndpointConnectionError -- Could not connect to the endpoint URL: "https://sts.us-east.amazonaws.com/"`
```
**How to reproduce it**
1. What command are you running?

prowler aws

3. Cloud provider you are launching

aws

4. Environment you have like single account, multi-account, organizations, multi or single subsctiption, etc.

organization

5. See error

`
2023-01-04 16:04:37,934 [File: audit_info.py:30] 	[Module: audit_info]	 CRITICAL: EndpointConnectionError -- Could not connect to the endpoint URL: "https://sts.us-east.amazonaws.com/"
`

Note: that domain name no longer resolves to any IP address.

**Expected behavior**

**Screenshots or Logs**
Also, you can add logs (anonymize them first!). Here a command that may help to share a log
`prowler <your arguments> --log-level DEBUG --log-file $(date +%F)_debug.log` then attach here the log file.

(there seem to be other instances in the code of names that do not resolve to IP addresses)

**From where are you running Prowler?**
Please, complete the following information:
 - Resource: (e.g. EC2 instance, Fargate task, Docker container manually, EKS, Cloud9, CodeBuild, workstation, etc.)

VM instance (neither AWS nor GCP) 

- OS: [e.g. Amazon Linux 2, Mac, Alpine, Windows, etc. ]

"Ubuntu 22.04.1 LTS"

 - Prowler Version [`./prowler --version`]:

Prowler 3.0.1

 - Python version [`python --version`]:

python3 --version
Python 3.10.6

 - Pip version [`pip --version`]:
pip --version
pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)

 - Installation method (Are you running it from pip package or cloning the github repo?):

pip package 

- Others:

**Additional context**

**Comment by SrikanthREEF** [comment] 2023-01-04 17:25
Running in to same issue in AWS EC2 Ubuntu 22.04.1 LTS . Running against single AWS account.  Every other resource is same as above user.

**Comment by toniblyx** [comment] 2023-01-04 18:45
Thanks for reporting this to us. That seems too weird because there is not such an endpoint like sts.us-east.amazonaws.com. us-east is not a valid region actually. Can you see if you have anything wrong in your AWS configuration?

1. First I would try with `prowler aws --region us-east-1` if that works means your AWS configuration is not correct.
2. I would review all my environment variables and configuration related to AWS doing `env | grep AWS` or `echo $AWS_STS_REGIONAL_ENDPOINTS` or looking at `~/.aws/config` and `~/.aws/credentials`. 

Please, let us know what you both get.

**Comment by SrikanthREEF** [comment] 2023-01-04 19:55
[](url)Hi @toniblyx  thanks for your quick response. 
I realized that I haven't shared what I see as an outcome in my earlier comment.  So, the attachment is from earlier attempt that confirms my creds and config is correct. I attempted this on 2 ubuntu boxes and every time scan hangs at 48% and it messes up connectivity to my box. I would have to restart the EC2 to retry again. I am assuming this may be conflicting or changing firewall config of the machine preventing host resolution or port 22 connectivity.


![image](https://user-images.githubusercontent.com/110049394/210637784-0e0118fd-9d50-472a-9ad7-1b4e76ce59aa.png)

**Comment by n4ch04** [comment] 2023-01-05 08:50
Hi @SrikanthREEF since the scan get hanged and you loose connectivity every time, it seems that you have a low ulimit set on your ubuntu ec2 instances. In Unix the ulimit sets the maximum file descriptors open at the same time, and the system treat as file descriptor almost everything (from sockets to proper files). Prowler, uses Python paginators, which creates intermediate files to process large API responses.
Give a try to the ulimit change setting, first check the current value with `ulimit -a` and then change it with `ulimit -n <value>`

**Comment by toniblyx** [comment] 2023-01-05 11:42
We are mixing issues here, the SSH connection reset issue commented by @SrikanthREEF has been moved to https://github.com/prowler-cloud/prowler/issues/1659 

We will keep here the issue with AWS STS Endpoints as requested by @fgont

**Comment by n4ch04** [comment] 2023-01-19 08:31
Hi @fgont, did the previous workaround solve your issue?

**Comment by n4ch04** [comment] 2023-01-23 08:30
Hi @fgont since we are not receiving feedback from your side we assume that the issue is solved. 
We are going to close the issue, feel free to reopen or open another one if the issue persist.

Thanks for using Prowler !!

**Closed as completed by n4ch04** 2023-01-23 08:31 UTC
Labels: bug, status/awaiting-reponse, severity/low

**Comment by bobbyhiddn** [comment] 2024-10-17 22:22
Dealing with this issue in gov-cloud where the suffix amazonaws.com is not correct. This is the relevant snippet from aws_provider.py:

```
    @staticmethod
    def create_sts_session(
        session: Session, aws_region: str = AWS_STS_GLOBAL_ENDPOINT_REGION
    ) -> Session.client:
        """
        Create an STS session client.

        Parameters:
        - session (session.Session): The AWS session object.
        - aws_region (str): The AWS region to use for the session.

        Returns:
        - session.Session.client: The STS session client.

        Example:
            session = boto3.session.Session()
            sts_client = create_sts_session(session, 'us-west-2')
        """
        try:
            sts_endpoint_url = (
                f"https://sts.{aws_region}.amazonaws.com"
                if not aws_region.startswith("cn-")
                else f"https://sts.{aws_region}.amazonaws.com.cn"
            )
            return session.client("sts", aws_region, endpoint_url=sts_endpoint_url)
        except Exception as error:
            logger.critical(
                f"{error.__class__.__name__}[{error.__traceback__.tb_lineno}]: {error}"
            )
            raise error
```

If this function allowed for an environmental variable override like with region, we would be set, but we are currently having to build a custom version of the library.
