### ISSUE TITLE
[Bug]: Prowler -v

### ISSUE THREAD

**Issue by BachateroJ** [toniblyx/prowler#1669] opened 2023-01-08 17:22 UTC
Hey, trying to run prowler and facing the following error:

assaf@assaf-VirtualBox:~$ prowler -v
Traceback (most recent call last):
  File "/home/assaf/.local/bin/prowler", line 5, in <module>
    from prowler.__main__ import prowler
  File "/home/assaf/.local/lib/python3.9/site-packages/prowler/__main__.py", line 38, in <module>
    from prowler.providers.common.audit_info import set_provider_audit_info
  File "/home/assaf/.local/lib/python3.9/site-packages/prowler/providers/common/audit_info.py", line 16, in <module>
    from prowler.providers.azure.azure_provider import Azure_Provider
  File "/home/assaf/.local/lib/python3.9/site-packages/prowler/providers/azure/azure_provider.py", line 5, in <module>
    from azure.mgmt.subscription import SubscriptionClient
  File "/home/assaf/.local/lib/python3.9/site-packages/azure/mgmt/subscription/__init__.py", line 9, in <module>
    from ._subscription_client import SubscriptionClient
  File "/home/assaf/.local/lib/python3.9/site-packages/azure/mgmt/subscription/_subscription_client.py", line 16, in <module>
    from ._configuration import SubscriptionClientConfiguration
  File "/home/assaf/.local/lib/python3.9/site-packages/azure/mgmt/subscription/_configuration.py", line 13, in <module>
    from azure.mgmt.core.policies import ARMChallengeAuthenticationPolicy, ARMHttpLoggingPolicy
**ImportError: cannot import name 'ARMChallengeAuthenticationPolicy' from 'azure.mgmt.core.policies' (/home/assaf/.local/lib/python3.9/site-packages/azure/mgmt/core/policies/__init__.py)**

the environment is ubuntu LTS 20.04.3
 python3.9 --version
Python 3.9.16

**Comment by n4ch04** [comment] 2023-01-09 08:16
Hi @BachateroJ  can you provide us a little bit more of information?
Are you launching prowler from the pip package or from the repo code?
What is the prowler version you are launching?

**Comment by BachateroJ** [comment] 2023-01-10 05:40
Hey.
it was installed via pip package, version 3

**Comment by n4ch04** [comment] 2023-01-10 11:35
Hi @BachateroJ please launch `prowler -v` to show exact version, since last version is `3.0.2`.
If yours does not match that please update the package and try again, to test if the issue persists

**Comment by BachateroJ** [comment] 2023-01-10 11:47
hey
prowler -v doesnt work for me, i get the error i mentioned above:

~$ prowler -v
Traceback (most recent call last):
  File "/home/assaf/.local/bin/prowler", line 5, in <module>
    from prowler.__main__ import prowler
  File "/home/assaf/.local/lib/python3.9/site-packages/prowler/__main__.py", line 38, in <module>
    from prowler.providers.common.audit_info import set_provider_audit_info
  File "/home/assaf/.local/lib/python3.9/site-packages/prowler/providers/common/audit_info.py", line 16, in <module>
    from prowler.providers.azure.azure_provider import Azure_Provider
  File "/home/assaf/.local/lib/python3.9/site-packages/prowler/providers/azure/azure_provider.py", line 5, in <module>
    from azure.mgmt.subscription import SubscriptionClient
  File "/home/assaf/.local/lib/python3.9/site-packages/azure/mgmt/subscription/__init__.py", line 9, in <module>
    from ._subscription_client import SubscriptionClient
  File "/home/assaf/.local/lib/python3.9/site-packages/azure/mgmt/subscription/_subscription_client.py", line 16, in <module>
    from ._configuration import SubscriptionClientConfiguration
  File "/home/assaf/.local/lib/python3.9/site-packages/azure/mgmt/subscription/_configuration.py", line 13, in <module>
    from azure.mgmt.core.policies import ARMChallengeAuthenticationPolicy, ARMHttpLoggingPolicy
ImportError: cannot import name 'ARMChallengeAuthenticationPolicy' from 'azure.mgmt.core.policies' (/home/assaf/.local/lib/python3.9/site-packages/azure/mgmt/core/policies/__init__.py)

**Comment by n4ch04** [comment] 2023-01-10 14:52
Sorry @BachateroJ, yes, difficult to get the version when the `-v` flag is not working.
Can you uninstall it with pip and install it again to ensure that version `3.0.2` is the one installed?
It can be retrieved from the installation process with pip

**Comment by BachateroJ** [comment] 2023-01-11 12:39
it seems that after uninstalling and installing again it began working again. 
another question, im performing a scan on an azure subscription and get only json and csv outputs, no html.
Detailed results are in:
 - CSV: /home/assaf/output/prowler-output-6a7f140107.csv
 - JSON: /home/assaf/output/prowler-output-6a7f140107.json

i tried using this command in order to create an html report: prowler azure --az-cli-auth -M html but the results look blank:
Detailed results are in:
assaf@assaf-VirtualBox:~$ 
is 3.0.2 supposed to generate html for azure, or only for aws?

Edit: i checked the csv file, it seems empty although i can clearly see in the terminal that the account was scanned and there were lots of fails - 

> Scan completed! |▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉| 20/20 [10

Overview Results:
╭─────────────────────┬─────────────────────╮
│ 46.84% (200) Failed │ 53.16% (227) Passed │
╰─────────────────────┴─────────────────────╯

Tenant ID/s 6a7f95ca634 Scan Results (severity columns are for fails only):

Subscriptions scanned: 1,2,3
╭────────────┬───────────┬────────────┬────────────┬────────┬──────────┬───────╮
│ Provider   │ Service   │ Status     │   Critical │   High │   Medium │   Low │
├────────────┼───────────┼────────────┼────────────┼────────┼──────────┼───────┤
│ azure      │ storage   │ FAIL (200) │          0 │     61 │       78 │    61 │
╰────────────┴───────────┴────────────┴────────────┴────────┴──────────┴───────╯
* You only see here those services that contains resources.

**Comment by n4ch04** [comment] 2023-01-12 11:11
Hi @BachateroJ 
Yes, that is an expected behaviour, the outputs files are still not enabled for Azure provider. We will cover it as soon as we can.
Can we help you with something else?

**Comment by n4ch04** [comment] 2023-01-17 07:54
Hi @BachateroJ since we did not get more feedback from your side we are going to close this issue, please feel free to reopen or create a PR with a workaround.

Thanks for using Prowler!!

**Closed as completed by n4ch04** 2023-01-17 07:54 UTC
Labels: bug, status/awaiting-reponse, severity/low
