### ISSUE TITLE
[Bug]: Unable to access the prowler dashboard from aws ec2 instance which has public IP

### ISSUE THREAD

**Issue by HanumanthaRAON** [toniblyx/prowler#3891] opened 2024-04-29 22:53 UTC
### Steps to Reproduce

1) As per the documentation we are running below command , we are running latest prowler version
 prowler -v
Prowler 4.1.0 (You are running the latest version, yay!)

$) prowler dashboard

![image](https://github.com/prowler-cloud/prowler/assets/20111534/d02d1300-cf8b-48d8-b901-15e5ffccf093)

we have also opened above mentioned port in aws security group but unable to access the dashboard . Can someone help us to get access the dashboard from outside of ec2 instance

### Expected behavior

As per the documentation we can access the dashboard after above steps mentioned 

### Actual Result with Screenshots or Logs

prowler dashboard --log-level DEBUG --log-file $(date +%F)_debug.log
usage: prowler [-h] [--version] {aws,azure,gcp,kubernetes,dashboard} ...
prowler: error: unrecognized arguments: --log-level DEBUG --log-file 2024-04-29_debug.log

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

ec2 insatnce

### OS used

Amazon Linux release 2023 (Amazon Linux)

### Prowler version

 prowler -v Prowler 4.1.0 (You are running the latest version, yay!)

### Pip version

pip --version pip 21.3.1 from /usr/lib/python3.9/site-packages/pip (python 3.9)

### Context

Not sure what did we missed

**Comment by jfagoagas** [comment] 2024-04-30 05:49
Hi @HanumanthaRAON, the behaviour you are describing is not a bug. **The dashboard server is not authenticated, if you expose it to the internet, you are running it at your own risk.**

With that said you can make it to listen in a different network interface with `HOST=0.0.0.0 prowler dashboard`. Please refer to our documentation [here](https://docs.prowler.com/projects/prowler-open-source/en/latest/tutorials/dashboard/) to know 

Thanks for using Prowler 🚀

**Comment by HanumanthaRAON** [comment] 2024-04-30 06:11
@jfagoagas , Thanks for your reply, But I am running the prowler on docker to expose it. How to expose the dashboard if we are running locally in Ec2 server.

Even if we run the docker the default location it is taking /home/prowler/outputs/ but currently I don't have that location on my server.

Please suggest on this

**Comment by jfagoagas** [comment] 2024-04-30 11:17
Hi @HanumanthaRAON as you can see in the Prowler documentation [here](https://docs.prowler.com/projects/prowler-open-source/en/latest/tutorials/dashboard/) for a docker container you can run `docker run --env HOST=0.0.0.0 --publish 127.0.0.1:11666:11666 toniblyx/prowler:latest dashboard` to expose the service in a different network interface.

If you want to access the internal `outputs` path you need to use Docker Volumes, refer [here](https://docs.docker.com/storage/volumes/) for more documentation about it. You can use the `-v` flag to map volumes within the host and the container.

**Comment by jfagoagas** [comment] 2024-05-03 07:05
Hi @HanumanthaRAON, I'm closing this issue. Please feel free to comment anything if you need more help. You can join our Slack channel with this [invite](https://join.slack.com/t/prowler-workspace/shared_invite/zt-2g0n47p1j-oFiW8QmY7a4rw9IV8H9HSg) where you can find guidance and support too.

Thanks for using Prowler 🚀

**Closed as completed by jfagoagas** 2024-05-03 07:05 UTC
Labels: question
