### ISSUE TITLE
[Bug]: False positive on check - "Check if SQS queues have policy set as Public"

### ISSUE THREAD

**Issue by yuliang29** [toniblyx/prowler#3212] opened 2023-12-20 01:41 UTC
### Steps to Reproduce

1. Typical prowler AWS scan command
2. AWS
3. Single
4. No error, more like false positive

### Expected behavior

I have a SQS access policy, with S3 ARN in the condition, which is for S3 event send to SQS, for example
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": "*",
      "Action": "sqs:SendMessage",
      "Resource": "arn:aws:sqs:*:*:<sqs_name>",
      "Condition": {
        "ArnEquals": {
          "aws:SourceArn": "arn:aws:s3:::<s3_name>"
        }
      }
    }
  ]
}
```

As S3 ARN does not have account id in it, the check here likely think it is not a valid condition.
https://github.com/prowler-cloud/prowler/blob/78505cb0a8e240cdceebd436335f68f941997853/prowler/providers/aws/lib/policy_condition_parser/policy_condition_parser.py#L75

### Actual Result with Screenshots or Logs

```
SQS queue is public because its policy allows public access, and the condition does not limit access to resources within the same account.
```

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

CLI locally

### OS used

MacOS

### Prowler version

3.11.3

### Pip version

23.1

**Comment by SimardeepSingh-zsh** [comment] 2023-12-30 21:02
Hi @yuliang29,

Thank you for reporting this issue and providing detailed steps to reproduce the false positive scenario in the Prowler AWS scan.

From the provided SQS access policy snippet, it seems that the condition indeed limits access based on the source S3 ARN, even though it lacks the account ID. This may be causing the misinterpretation in our policy condition parser.

To address this false positive, here are some insights and possible workarounds:

Policy Condition Parsing: The current policy condition parser might not accurately interpret conditions without explicit account IDs. This could lead to false positives, especially in scenarios where conditions are based solely on resource ARNs without account specifics.

Parser Enhancement: We can consider enhancing the parser logic to handle scenarios like the one you've described, where conditions might lack explicit account IDs but still have valid restrictions based on resource ARNs.

Adjusting Policies: In the meantime, as a workaround, you might explicitly specify the AWS account ID in your conditions wherever possible to ensure accurate evaluation by the policy parser.

**Comment by jfagoagas** [comment] 2024-02-16 06:55
Hi @yuliang29 @SimardeepSingh-zsh I was checking this issue and I noticed that this is fixed in the `master` branch. As you can see in this part of the code https://github.com/prowler-cloud/prowler/blob/master/prowler/providers/aws/lib/policy_condition_parser/policy_condition_parser.py#L24-L43, we are handling the `aws:SourceArn` using the `ArnEquals` condition, so that check will raise a `PASS` finding for a SQS queue with that policy.

I'm going to close it since it is no longer an issue. Please feel free to reopen it if you notice the same behaviour again.


Thanks for using Prowler 🚀

**Closed as completed by jfagoagas** 2024-02-16 06:55 UTC
Labels: bug, provider/aws
